source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

target 'MortgageCalculator' do
  pod 'Google-Mobile-Ads-SDK'
pod 'Bugly', '2.4.2'
pod 'IQKeyboardManager'
pod 'Masonry', '1.0.2'
pod 'YYModel', '1.0.4'
end
